name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: almlcontainer.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t almlcontainer.azurecr.io/my-fast-api:latest .
          docker push almlcontainer.azurecr.io/my-fast-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: alml
          images: almlcontainer.azurecr.io/my-fast-api:latest
          slot-name: 'production'
          azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          service-principal-id: ${{ secrets.AZURE_CLIENT_ID }}
          service-principal-key: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
